version: '3.4'

services:
  finance-management-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      HOST: "postgres"
      PORT: "5432"
      USERNAME: "postgres"
      PASSWORD: "Postgres2019!"
      DATABASE: "FinanceManagement"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "63732:63732"
      - "44374:44374"
    depends_on: 
      - postgres
    networks: 
      - compose-network
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    networks: 
      - compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@financemanagement.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "1234:80"
    depends_on: 
      - postgres
    networks: 
      - compose-network

networks:
  compose-network:
    driver: bridge